### ISSUE TITLE
Manual TLS doesnt work for me

### ISSUE THREAD

**Issue by KevinGrub** [algolia/sup3rS3cretMes5age#65]
Hi guys, 

hopefully somebody can help me. I'm not able to solve this Problem by myself.
I get some issues when I try to run sup3rS3cretMes5age with Manual TLS and i don't know what I'm doing wrong.
Over HTTP it works fine.

Here is my docker-compose.yml

I always get the error: 

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.supersecret.environment contains an invalid type, it should be an object, or an array

This problem is making me Headache. Please Help... Don't know what to try anymore.

----------------------------------------------------------------------------------------------------------------------------

version: '3.2'

services:
  vault:
    image: vault:latest
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: supersecret
    cap_add:
      - IPC_LOCK
    expose:
      - 8200

  supersecret:
    build: ./
    image: algolia/supersecretmessage:latest
    container_name: supersecret
    environment:
       VAULT_ADDR=http://vault:8200
      VAULT_TOKEN=root
      SUPERSECRETMESSAGE_HTTPS_BINDING_ADDRESS=:443
      SUPERSECRETMESSAGE_TLS_CERT_FILEPATH=/path/to/my/cert/fullchain.pem
      SUPERSECRETMESSAGE_TLS_CERT_KEY_FILEPATH=/path/to/my/key/privkey.pem
    ports:
      - "8082:8082"
    depends_on:
      - vault

----------------------------------------------------------------------------------------------------------------------------

**Comment by eranchetz** [comment]
Looks like your yaml file is not well formatted 
check out this example: https://github.com/algolia/sup3rS3cretMes5age/blob/master/docker-compose.yml 
1. Make sure you have the right indentation 
2. make sure you use a colon `:` and not an equal `=` for env var assignment

**Comment by KevinGrub** [comment]
sup3rS3cretMes5age only works with http for me.

**Comment by eranchetz** [comment]
Looks like the README is indeed missing an example of that.
Here is how you do this: 

I created a self signed cert (you can use your signed one of course)

`openssl req -x509 -nodes -subj '/CN=localhost'  -newkey rsa:4096 -keyout ./key.pem -out ./tls/cert.pem -days 365`

This is the docker-compose.yml I used, notice the `volumes` section and the `environment` section
```
version: '3.2'

services:
  vault:
    image: vault:latest
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: supersecret
    cap_add:
      - IPC_LOCK
    expose:
      - 8200

  supersecret:
    build: ./
    image: algolia/supersecretmessage:latest
    container_name: supersecret
    volumes:
      - ./tls/:/mnt
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: supersecret
      SUPERSECRETMESSAGE_HTTPS_BINDING_ADDRESS: ":8082"
      SUPERSECRETMESSAGE_TLS_CERT_FILEPATH: "/mnt/cert.pem"
      SUPERSECRETMESSAGE_TLS_CERT_KEY_FILEPATH: "/mnt/key.pem"
    ports:
      - "8082:8082"
    depends_on:
      - vault
```

<img width="636" alt="image" src="https://user-images.githubusercontent.com/357094/181242258-de23319e-0ed5-47af-9b5a-1d0ce39b6ac4.png">
